config/routes.rb
Rails.application.routes.draw do
  


  #Contact Us Pg
  resources :contacts

  devise_for :users
  devise_for :views
  
  #Adoptable dogs on Michigan Pg
  get 'michigan' => 'dogs#michigan'
  post 'michigan' => 'dogs#michigan'

  #Adoptable dogs on Michigan Pg
  get 'foster' => 'dogs#foster'
  post 'foster' => 'dogs#foster'

  resources :dogs

  #Display Ways To Help Pg 
  get 'welcome/help'

  #Events Pg
  get 'welcome/events'

  #Display using carousel btn
  post 'welcome/events'

  get 'welcome/index'

  get 'welcome/about'

  #Button link
  post 'welcome/about'

  #Journey Pg
  get 'welcome/show'

  root to: 'welcome#index' 
end

app/models/dog.rb
class Dog < ActiveRecord::Base 

  #Filter status decides which view dogs will be displayed on
  scope :foster, -> { where status: 'Foster' }
  scope :adoptable, -> { where status: 'Adoptable' }
  scope :pending, -> { where status: 'Pending' }
  scope :homed, -> { where status: 'Homed' }
  scope :expired, -> { where status: 'Expired' }

  before_save :set_breedtype, :capitalize_dog_name

  attr_accessor :status_choice, :gender_choice, :age_choice, :breed_choice, :cat_choice, :dog_choice, :human_choice, 
                 :energy_choice, :temperament_choice, :image, :image_cache, :remote_image_url
  
  mount_uploader :image, ImageUploader

  #validates :animal_id, presence: true 
  validates :name, presence: true
  validates :age, presence: true
  validates :status, presence: true
  validates :gender, presence: true
  validates :weight, numericality: { only_integer: true }, presence: true
  validates :breed_type, presence: true 
  validates :breed_one, presence: true
  validates :breed_two, presence: true
  validates :cat_compatible, presence: true
  validates :dog_compatible, presence: true
  validates :human_compatible, presence: true
  validates :energy_level, presence: true
  validates :temperament, presence: true
  validates :fee, numericality: { only_integer: true }, presence: true
  validates :description, presence: true
  validates :image, presence: true

             

  private
    #Set default for secondary breed_type if purebred is selected
    def set_breedtype
      if breed_type == "Purebreed" 
        self.breed_two = "Not applicable"    
    end

    #Capitalize dog names with spaces
    def capitalize_dog_name
      new_name = name.split(" ").each{|i| i.capitalize!}.join(" ")
      self.name = new_name
    end

  end


  STATUS_CHOICE = ['Foster', 'Adoptable']
  GENDER_CHOICE = ['Neutered Male', 'Unaltered Male', 'Spayed Female', 'Unaltered Female']
  AGE_CHOICE = ['2 Months', '3 Months', '4 Months', '5 Months', '6 Months', '7 Months', '8 Months', '9 Months', '10 Months', '11 Months', '1 Year', '2 Years', 
    '3 Years', '4 Years', '5 Years', '6 Years', '7 Years', '8 Years', '9 Years', '10 Years', '11 Years', '12 Years']
  CAT_CHOICE = ['Unknown', 'Good with cats', 'Not good with cats']
  DOG_CHOICE = ['Unknown', 'Good with dogs', 'Good with male dogs only', 'Good with female dogs only', 'Not good with other dogs']
  HUMAN_CHOICE = ['Good with women only', 'Good with men only', 'Good with adults & kids', 'Not good with kids']
  ENERGY_CHOICE = ['Very low', 'Low', 'Average', 'High', 'Very high']
  TEMPERAMENT_CHOICE = ['Very submissive', 'Somewhat submissive', 'Average submissive', 'Somewhat dominant', 'Very dominant']
  
  BREED_CHOICE = 
  [
  'Not Applicable',
  'Affenpinscher', 
  'Afghan Hound ',
  'Airedale Terrier', 
  'Akita', 
  'Alaskan Malamute', 
  'American English Coonhound', 
  'American Eskimo Dog (Miniature)', 
  'American Eskimo Dog (Standard)', 
  'American Eskimo Dog (Toy)', 
  'American Foxhound', 
  'American Hairless Terrier',
  'American Staffordshire Terrier', 
  'American Water Spaniel', 
  'Anatolian Shepherd Dog', 
  'Australian Cattle Dog', 
  'Australian Shepherd', 
  'Australian Terrier', 
  'Basenji', 
  'Basset Hound', 
  'Beagle', 
  'Bearded Collie', 
  'Beauceron', 
  'Bedlington Terrier', 
  'Belgian Malinois', 
  'Belgian Sheepdog', 
  'Belgian Tervuren', 
  'Bergamasco', 
  'Berger Picard', 
  'Bernese Mountain Dog', 
  'Bichon FrisÈ', 
  'Black and Tan Coonhound', 
  'Black Russian Terrier', 
  'Bloodhound', 
  'Bluetick Coonhound', 
  'Boerboel', 
  'Border Collie', 
  'Border Terrier', 
  'Borzoi', 
  'Boston Terrier', 
  'Bouvier des Flandres', 
  'Boxer', 
  'Boykin Spaniel', 
  'Briard', 
  'Brittany', 
  'Brussels Griffon', 
  'Bull Terrier', 
  'Bull Terrier (Miniature)', 
  'Bulldog', 
  'Bullmastiff', 
  'Clumber Spaniel',
  'Cairn Terrier', 
  'Canaan Dog', 
  'Cane Corso', 
  'Cardigan Welsh Corgi', 
  'Cavalier King Charles Spaniel', 
  'Cesky Terrier', 
  'Chesapeake Bay Retriever', 
  'Chihuahua', 
  'Chinese Crested Dog', 
  'Chinese Shar Pei', 
  'Chinook', 
  'Chow Chow', 
  'Cirneco dellEtna', 
  'Clumber Spaniel', 
  'Cocker Spaniel', 
  'Collie', 
  'Coton de Tulear', 
  'Curly-Coated Retriever', 
  'Dachshund', 
  'Dalmatian', 
  'Dandie Dinmont Terrier', 
  'Doberman Pinscher', 
  'Dogue de Bordeaux', 
  'English Cocker Spaniel', 
  'English Foxhound', 
  'English Setter', 
  'English Springer Spaniel', 
  'English Toy Spaniel', 
  'Entlebucher Mountain Dog', 
  'Field Spaniel', 
  'Finnish Lapphund', 
  'Finnish Spitz', 
  'Flat-Coated Retriever', 
  'French Bulldog', 
  'German Pinscher', 
  'German Shepherd Dog', 
  'German Shorthaired Pointer', 
  'German Wirehaired Pointer', 
  'Giant Schnauzer', 
  'Glen of Imaal Terrier', 
  'Golden Retriever', 
  'Gordon Setter', 
  'Great Dane', 
  'Great Pyrenees', 
  'Greater Swiss Mountain Dog', 
  'Greyhound', 
  'Harrier', 
  'Havanese', 
  'Ibizan Hound', 
  'Icelandic Sheepdog', 
  'Irish Red and White Setter', 
  'Irish Setter', 
  'Irish Terrier', 
  'Irish Water Spaniel', 
  'Irish Wolfhound', 
  'Italian Greyhound', 
  'Japanese Chin', 
  'Keeshond', 
  'Kerry Blue Terrier', 
  'Komondor', 
  'Kuvasz', 
  'Labrador Retriever', 
  'Lagotto Romagnolo', 
  'Lakeland Terrier', 
  'Leonberger', 
  'Lhasa Apso', 
  'Lˆwchen', 
  'Miniature Schnauzer',
  'Maltese', 
  'Manchester Terrier', 
  'Mastiff', 
  'Miniature American Shepherd', 
  'Miniature Bull Terrier', 
  'Miniature Pinscher', 
  'Miniature Schnauzer', 
  'Neapolitan Mastiff', 
  'Newfoundland', 
  'Norfolk Terrier', 
  'Norwegian Buhund', 
  'Norwegian Elkhound', 
  'Norwegian Lundehund', 
  'Norwich Terrier', 
  'Nova Scotia Duck-Tolling Retriever', 
  'Old English Sheepdog', 
  'Otterhound', 
  'Papillon', 
  'Parson Russell Terrier', 
  'Pekingese', 
  'Pembroke Welsh Corgi', 
  'Petit Basset Griffon VendÈen', 
  'Pharaoh Hound', 
  'Plott', 
  'Pointer', 
  'Polish Lowland Sheepdog', 
  'Pomeranian', 
  'Poodle',  
  'Portuguese Podengo Pequeno', 
  'Portuguese Water Dog', 
  'Pug', 
  'Puli', 
  'Pyrenean Shepherd', 
  'Rat Terrier', 
  'Redbone Coonhound', 
  'Rhodesian Ridgeback', 
  'Rottweiler', 
  'Russell Terrier', 
  'St. Bernard', 
  'Saluki', 
  'Samoyed', 
  'Schipperke', 
  'Scottish Deerhound', 
  'Scottish Terrier', 
  'Sealyham Terrier', 
  'Shetland Sheepdog', 
  'Shiba Inu', 
  'Shih Tzu', 
  'Siberian Husky', 
  'Silky Terrier', 
  'Skye Terrier', 
  'Sloughi', 
  'Smooth Fox Terrier', 
  'Soft-Coated Wheaten Terrier', 
  'Spanish Water Dog', 
  'Staffordshire Bull Terrier', 
  'Standard Schnauzer', 
  'Sussex Spaniel', 
  'Swedish Vallhund', 
  'Tibetan Mastiff', 
  'Tibetan Spaniel', 
  'Tibetan Terrier', 
  'Toy Fox Terrier', 
  'Treeing Walker Coonhound', 
  'Vizsla', 
  'Weimaraner', 
  'Welsh Springer Spaniel', 
  'Welsh Terrier', 
  'West Highland White Terrier', 
  'Whippet', 
  'Wire Fox Terrier', 
  'Wirehaired Pointing Griffon', 
  'Wirehaired Vizsla', 
  'Xoloitzcuintli', 
  'Yorkshire Terrier'
  ]
end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController

  
  def index
    @dogs = Dog.all
  end

  #Display only 12 foster dogs on index.html.erb
  def foster
    @dogs = Dog.foster.paginate(page: params[:page], per_page: 12)
  end

  #Display only 12 adoptable dogs on michigan.html.erb
  def michigan
    @dogs = Dog.adoptable.paginate(page: params[:page], per_page: 12)
  end
  
  def show
  	@dog = Dog.find(params[:id])
  end

  def new
  	@dog = Dog.new
  end

  def edit
  	@dog = Dog.find(params[:id])
  end

  def create
  	@dog = Dog.new(dog_params)
    if @dog.save
      flash[:notice] = "Dog was saved successfully."
      redirect_to @dog
    else
      flash[:error] = "Error: #{@dog.errors.full_messages}."
      render :new 
    end 

  end

  def update
    @dog = Dog.find(params[:id])  
    if @dog.update_attributes(dog_params)
       flash[:notice] = "Update successful."
       redirect_to @dog
    else
      flash[:error] = "Error saving input. Please try again."
      render :edit
    end
  end

  def destroy
  	@dog = Dog.find(dog_params[:id])
  	if @dog.destroy
      flash[:notice] = "Dog has been removed."
      redirect_to @dog
    else
      flash[:error] = "Error: #{@dog.errors.full_messages}."
    end
  end


  private
  def dog_params
  params.require(:dog).permit(:animal_id, :name, :status, :gender, :weight, :age, :breed_type, :breed_one, :breed_two,
         :cat_compatible, :dog_compatible, :human_compatible, :energy_level, :temperament, :fee, :description, :image)
  end
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/views/dogs/_form.html.erb
<!-- Used for entering all data for a new dog -->
<!-- Styling supported by dogs.scss -->

<div class="col-md-6 col-md-offset-3">
  <h1 id="adoptable-title">Add A New Dog</h1>
    <div class="form-traits">

      <%= simple_form_for @dog do |f| %>
    
        <div class="errors">
          <% if @dog.errors.any? %>
            <h2>There are <%= pluralize(@dog.errors.count, "error") %></h2>
              <ul>
                <% @dog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
          <% end %>
        </div> 

      <%= f.input :animal_id, label: 'Animal ID' %>
      <%= f.input :name %>
      <%= f.input :status, collection: Dog::STATUS_CHOICE, label: 'Status' %>
      <%= f.input :gender, collection: Dog::GENDER_CHOICE, label: 'Gender' %>
      <%= f.input :weight, as: :integer %> 
      <%= f.input :age, collection: Dog::AGE_CHOICE, label: 'Age' %> 
      <%= f.input :breed_type, as: :radio_buttons, collection: ['Purebreed', 'Blend'] %>
      <%= f.input :breed_one, collection: Dog::BREED_CHOICE, label: 'Breed One' %> 
      <%= f.input :breed_two, collection: Dog::BREED_CHOICE, label: 'Breed Two' %>          
      <%= f.input :cat_compatible, collection: Dog::CAT_CHOICE, label: 'Cat Compatibility' %> 
      <%= f.input :dog_compatible, collection: Dog::DOG_CHOICE, label: 'Dog Compatibility' %>
      <%= f.input :human_compatible, collection: Dog::HUMAN_CHOICE, label: 'Human Compatibility' %>
      <%= f.input :energy_level, collection: Dog::ENERGY_CHOICE, label: 'Energy Level' %> 
      <%= f.input :temperament, collection: Dog::TEMPERAMENT_CHOICE, label: 'Temperament' %> 
      <%= f.input :fee, as: :integer  %>
      <%= f.text_area :description, label: 'Description', rows: 8, class: "info-box", placeholder: 'Add additional information.' %>
      <%= f.file_field :image, class: "upload" %>
      <%= f.label :remote_image_url, "or image URL" %>
      <p><%= f.text_field :remote_image_url %></p>
      <% f.hidden_field :image_cache %>
      <%= f.submit "Submit", class: 'btn btn-success center-block' %>
    <% end %>
    </div>
</div>

app/views/dogs/_paypal.html.erb
<!-- PayPal Logo -->
<table border="0" cellpadding="10" cellspacing="0" align="center">
  <tr>
    <td align="center">
    </td>
  </tr>
  <tr>
    <td align="center">
      <a href="https://www.paypal.com/webapps/mpp/paypal-popup" title="How PayPal Works" onclick="javascript:window.open('https://www.paypal.com/webapps/mpp/paypal-popup','WIPaypal','toolbar=no, location=no, directories=no, status=no, menubar=no, scrollbars=yes, resizable=yes, width=1060, height=700'); return false;">
      <img src="https://www.paypalobjects.com/webstatic/mktg/logo/pp_cc_mark_37x23.jpg" border="0" alt="PayPal Logo">
      </a>
  </td>
  </tr>
</table><!-- PayPal Logo -->

app/views/dogs/edit.html.erb
<!-- Used for editing existing dog -->
<!-- Styling supported by dogs.scss -->

<div class="col-md-6 col-md-offset-3">
  <h1 id="adoptable-title">Edit Dog</h1>
    <div class="form-traits">

      <%= simple_form_for @dog do |f| %>
    
        <div class="errors">
          <% if @dog.errors.any? %>
            <h2>There are <%= pluralize(@dog.errors.count, "error") %></h2>
              <ul>
                <% @dog.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
                <% end %>
              </ul>
          <% end %>
        </div> 

      <%= f.input :animal_id, label: 'Animal ID' %>
      <%= f.input :name %>
      <%= f.input :status, collection: Dog::STATUS_CHOICE, label: 'Status' %>
      <%= f.input :gender, collection: Dog::GENDER_CHOICE, label: 'Gender' %>
      <%= f.input :weight, as: :integer %> 
      <%= f.input :age, collection: Dog::AGE_CHOICE, label: 'Age' %> 
      <%= f.input :breed_type, as: :radio_buttons, collection: ['Purebreed', 'Blend'] %>
      <%= f.input :breed_one, collection: Dog::BREED_CHOICE, label: 'Breed One' %> 
      <%= f.input :breed_two, collection: Dog::BREED_CHOICE, label: 'Breed Two' %>          
      <%= f.input :cat_compatible, collection: Dog::CAT_CHOICE, label: 'Cat Compatibility' %> 
      <%= f.input :dog_compatible, collection: Dog::DOG_CHOICE, label: 'Dog Compatibility' %>
      <%= f.input :human_compatible, collection: Dog::HUMAN_CHOICE, label: 'Human Compatibility' %>
      <%= f.input :energy_level, collection: Dog::ENERGY_CHOICE, label: 'Energy Level' %> 
      <%= f.input :temperament, collection: Dog::TEMPERAMENT_CHOICE, label: 'Temperament' %> 
      <%= f.input :fee, as: :integer  %>
      <%= f.text_area :description, label: 'Description', rows: 8, class: "info-box", placeholder: 'Add additional information.' %>
      <%= f.file_field :image, class: "upload" %>
      <%= f.label :remote_image_url, "or image URL" %>
      <p><%= f.text_field :remote_image_url %></p>
      <% f.hidden_field :image_cache %>
      <%= f.submit "Submit", class: 'btn btn-success center-block' %>
    <% end %>
    </div>
</div>

app/views/dogs/foster.html.erb
<!-- Foster Dog page -->
<!-- Styling supported by dogs.scss -->

<div class="container-fluid">
  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="heading">Foster Dogs</h1>
      <p class="heading-description">Dogs on this page are located in the South Texas area. They will not be available for adoption, until they arrive in Michigan. However, you can begin the screening process early by submitting an application.</p>
    </div>
  </div>  

  <!-- 3 columns per row -->
  <% @dogs.each_slice(3) do |dogs| %>
    <div class="row"> 
      <% dogs.each do |dog| %> 
         <div class="col-md-4 foster-profile">
          <p><%= image_tag dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
          <h3 class="dog-title"><strong>Animal ID:</strong> <%= dog.animal_id %> | <strong>Name:</strong> <%= dog.name %></h3>
            <ul>
              <li class="dog-traits"><strong>Gender:</strong> <%= dog.gender %></li>
              <li class="dog-traits"><strong>Weight:</strong> <%= dog.weight %> lbs</li>
              <li class="dog-traits"><strong>Age:</strong> <%= dog.age %></li>
              <li class="dog-traits"><strong>Breed Type:</strong> <%= dog.breed_type %></li>
              <li class="dog-traits"><strong>Primary Breed:</strong> <%= dog.breed_one %></li>
              <li class="dog-traits"><strong>Secondary Breed:</strong> <%= dog.breed_two %></li>
              <li class="dog-traits"><strong>Cat Compatibility:</strong> <%= dog.cat_compatible %></li>
              <li class="dog-traits"><strong>Dog Compatibility:</strong> <%= dog.dog_compatible %></li>
              <li class="dog-traits"><strong>Human Compatibility:</strong> <%= dog.human_compatible %></li>
              <li class="dog-traits"><strong>Energy Level:</strong> <%= dog.energy_level %></li>
              <li class="dog-traits"><strong>Temperament:</strong> <%= dog.temperament %></li>
              <li class="dog-traits"><strong>Adoption Fee:</strong> $<%= dog.fee %></li>
            </ul>  
          <p class="dog-description"><%= dog.description %></p>
        </div><!-- /.col-md-4 foster-profile-->  
      <% end %>
    </div><!-- /.row space -->
  <% end %>
  <!-- Display 12 dogs per pg -->
  <div class="digg_pagination">
    <%= will_paginate @dogs %>
  </div>
</div><!-- /.container -->

app/views/dogs/michigan.html.erb
<!-- Adoptable Dog page -->
<!-- Styling supported by dogs.scss -->

<div class="container-fluid">
  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h2 class="heading">Adoptable Dogs</h1>
      <p class="heading-description">Dogs on this page are located in the Michigan area, and are ready for adoption. Please submit an application if you are interested in adopting.</p>
    </div>
  </div>   

  <!-- 3 columns per row -->
  <% @dogs.each_slice(3) do |dogs| %>
    <div class="row"> 
      <% dogs.each do |dog| %> 
         <div class="col-md-4 adoptable-profile">
          <p><%= image_tag dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
          <h3 class="dog-title"><strong>Animal ID:</strong> <%= dog.animal_id %> | <strong>Name:</strong> <%= dog.name %></h3>
            <ul>
              <li class="dog-traits"><strong>Gender:</strong> <%= dog.gender %></li>
              <li class="dog-traits"><strong>Weight:</strong> <%= dog.weight %> lbs</li>
              <li class="dog-traits"><strong>Age:</strong> <%= dog.age %></li>
              <li class="dog-traits"><strong>Breed Type:</strong> <%= dog.breed_type %></li>
              <li class="dog-traits"><strong>Primary Breed:</strong> <%= dog.breed_one %></li>
              <li class="dog-traits"><strong>Secondary Breed:</strong> <%= dog.breed_two %></li>
              <li class="dog-traits"><strong>Cat Compatibility:</strong> <%= dog.cat_compatible %></li>
              <li class="dog-traits"><strong>Dog Compatibility:</strong> <%= dog.dog_compatible %></li>
              <li class="dog-traits"><strong>Human Compatibility:</strong> <%= dog.human_compatible %></li>
              <li class="dog-traits"><strong>Energy Level:</strong> <%= dog.energy_level %></li>
              <li class="dog-traits"><strong>Temperament:</strong> <%= dog.temperament %></li>
              <li class="dog-traits"><strong>Adoption Fee:</strong> $<%= dog.fee %></li>
            </ul>  
          <p class="dog-description"><%= dog.description %></p>
        </div><!-- /.col-md-4 adoptable-profile-->  
      <% end %>
    </div><!-- /.row space -->
  <% end %>
  <!-- Display 12 dogs per pg -->
  <div class="digg_pagination">
    <%= will_paginate @dogs %>
  </div>
</div><!-- /.container -->

app/views/dogs/new.html.erb
<div class="container-fluid">
  <div class="row">
	<%= render 'dogs/form' %>
  </div>	
</div>

app/views/dogs/show.html.erb
<!-- Display single dog after being entered into form -->
<!-- Styling supported by dogs.scss -->
<div class="container-fluid">

  <!-- Page Header -->
  <div class="row">
    <div class="col-lg-12">
      <h1 class="heading">Individual Dog Info</h1>
      <p class="heading-description">This displays the dog you just entered. Click he <i><strong>Back</strong></i> to return to the <i><strong>Enter A New Dog</strong></i> page. Click the <i><strong>Edit</strong></i> button to make changes for any dog already added to either the Foster or Adoptable page.</p>
    </div>
  </div> 

  <div class="row">
    <div class="col-md-4">
      <%= link_to 'Back', new_dog_path, class: 'btn btn-primary pull-right' %> 
    </div>
    <div class="col-md-4">
      <div class="adoptable-profile">
        <p><%= image_tag @dog.image_url(:thumb), class: "img-responsive img-adoptable center-block" %><p>
        <h4 class="dog-title"><strong>Animal ID:</strong> <%= @dog.animal_id %> | <strong>Name:</strong> <%= @dog.name %></h4>
        <ul>
          <li class="dog-traits"><strong>Gender:</strong> <%= @dog.gender %></li>
          <li class="dog-traits"><strong>Weight:</strong> <%= @dog.weight %> lbs</li>
          <li class="dog-traits"><strong>Age:</strong> <%= @dog.age %></li>
          <li class="dog-traits"><strong>Breed Type:</strong> <%= @dog.breed_type %></li>
          <li class="dog-traits"><strong>Primary Breed:</strong> <%= @dog.breed_one %></li>
          <li class="dog-traits"><strong>Secondary Breed:</strong> <%= @dog.breed_two %></li>
          <li class="dog-traits"><strong>Cat Compatibility:</strong> <%= @dog.cat_compatible %></li>
          <li class="dog-traits"><strong>Dog Compatibility:</strong> <%= @dog.dog_compatible %></li>
          <li class="dog-traits"><strong>Human Compatibility:</strong> <%= @dog.human_compatible %></li>
          <li class="dog-traits"><strong>Energy Level:</strong> <%= @dog.energy_level %></li>
          <li class="dog-traits"><strong>Temperament:</strong> <%= @dog.temperament %></li>
          <li class="dog-traits"><strong>Adoption Fee:</strong> $<%= @dog.fee %></li>
        </ul>
        <p class="dog-description"><%= @dog.description %></p> 
      </div><!-- /.adoptable-profile -->
    </div><!-- /.col-md-3 -->
    <div class="col-md-4">
      <%= link_to 'Edit', edit_dog_path, class: 'btn btn-success pull-left' %> 
    </div>
  </div><!-- /.row -->  
</div><!-- /.container-fluid -->