config/routes.rb
Rails.application.routes.draw do
  


  #Contact Us Pg
  resources :contacts

  devise_for :users
  devise_for :views
  
  #Adoptable dogs on Michigan Pg
  get 'michigan' => 'dogs#michigan'
  post 'michigan' => 'dogs#michigan'

  #Adoptable dogs on Michigan Pg
  get 'foster' => 'dogs#foster'
  post 'foster' => 'dogs#foster'

  resources :dogs

  #Display Ways To Help Pg 
  get 'welcome/help'

  #Events Pg
  get 'welcome/events'

  #Display using carousel btn
  post 'welcome/events'

  get 'welcome/index'

  get 'welcome/about'

  #Button link
  post 'welcome/about'

  #Journey Pg
  get 'welcome/show'

  root to: 'welcome#index' 
end

app/views/shared/_carousel.html.erb
<!-- CAROUSEL -->

<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag("map_smoke.jpg", class: "center-block slide_1", alt: "First slide") %>
        <div class="container">
          <div class="carousel-caption">
            
          </div>
        </div>
    </div>
    <div class="item">
      <%= image_tag("belin_smoke.jpg", class: "center-block slide", alt: "Second slide") %>
        <div class="container">
          <div class="carousel-caption">
          </div>
        </div>
    </div>
      <div class="item">
        <img class="third-slide" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Help Support Our Cause!</h1>
              <h2>Tupperware Fundraiser</h2>
              <p>Through Oct. 31st, 2017</p>
              <p><%= button_to "Learn more", welcome_events_path, class: 'btn btn-lg btn-primary' %></p>
            </div>
          </div>
      </div>
  </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
</div><!-- /.carousel -->

app/views/shared/_footer.html.erb
<!-- Styling by welcome.scss -->

<footer class="container-fluid bg-blue">
  <div class="row">
    <div class="col-md-4">
      <p>Compass Dog Rescue<span class='glyphicon glyphicon-copyright-mark'></span> 2017 
      </p>
    </div>
    <div class="col-md-4 center-logos">
    <!-- Facebook Logo -->
      <p><%= link_to image_tag("FB-f-Logo__white_57.png", class: "img-responsive center-block"), "https://www.facebook.com/compassdogrescue/?fref=ts", alt: "Facebook Logo", target: "_blank" %>
      </p>
    </div>
    <div class="col-md-4">
      <p class="pull-right"><%= link_to "Back To Top", "#", class: "btn btn-footer" %>
      </p>
    </div>
  </div>
</footer>

   

app/views/shared/_navbar.html.erb
<!-- Fixed navbar -->
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to(image_tag("logo_04.png", class: "navbar-brand", alt: "Compass Logo"), root_path) %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_path, class: "navlink" %></li>
        <li><%= link_to "About", welcome_about_path, class: "navlink" %></li>
        <li><%= link_to "Events", welcome_events_path, class: "navlink" %></li>
        <li><%= link_to "Ways To Help", welcome_help_path, class: "navlink" %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Our Dogs<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Our Dogs Journey", welcome_show_path, class: "navlink-inverse" %></li>
              <li><%= link_to "Foster Dogs", foster_path, class: "navlink-inverse" %></li>
              <li><%= link_to "Adoptable Dogs", michigan_path, class: "navlink-inverse" %></li>
            </ul>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Applications<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Volunteer Application", welcome_show_path, class: "navlink-inverse" %></li>
                  <li><%= link_to "Foster Application", welcome_show_path, class: "navlink-inverse" %></li>
                  <li><%= link_to "Adoption Application", welcome_show_path, class: "navlink-inverse" %></li>
                </ul>
            </li>
          <li><%= link_to "Contact", new_contact_path, class: "navlink" %></li>
          <li><%= link_to "Log In", new_user_session_path, class: "navlink" %></li>
        </li>
      </ul><!-- nav navbar-nav -->
    </div><!--/.nav-collapse -->
  </div>
</nav>